
services:
  database:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=yyyyy
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  backend:
    build: ./    
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=yyyyy
      - DB_PASSWORD=1234
      - DB_NAME=mydb
    depends_on:
      - database
    links:
      - database

volumes:
  database-data:
    driver: local
